name: GoKV CI

on:
  push:
    branches: [ "*" ]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Lint
      run: go fmt ./...
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Lint
      run: go vet ./...
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: test
      run: go test ./...

  security-check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
          
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
  
      - name: vulncheck
        run: govulncheck ./...
  
  static-analysis:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
          
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
  
      - name: vulncheck
        run: staticcheck ./...
